export const COLOR = {
  MAIN_WHITE: "#ffffff",
  MAIN_BLACK: "#121212",
  MAIN: "#EB5844",
  MAIN_HOVER: "#EC7B6B",
  BRIGHT_GRAY: "#EEEEEE",
  LIGHT_GRAY: "#DEDEDE",
  MEDIUM_GRAY: "#9D9D9D",
  DARK_GRAY: "#535353",
};
